--- 
title: "5702 Final Project"
author: "Tianyu Han, Shijia Huang, Lin Gong"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction
New York City is among the most modern cities in the world, so is Los Angeles, San Francisco, and many more. These big cities in the United States are at the heart of transportation, tourism, etc., with people from diverse backgrounds around the world. Despite having a population of more than 8 million people, NYC consistently ranks in the top 10 safest large cities (defined as those with more than 500,000 residents) in the United States. It's generally considered safe for travelers, which is why the city sees more than 65 million visitors per year. However, crime happens, as within any major city in the world. For instance, if we pay attention to the news, the MTA has recently had many heartbreaking accidents including people being pushed down the railway or getting hit by an oncoming train. And there are other crimes such as burglary and arson happening in sub-areas in the city. All of which has huge impacts on our daily life as students studying and living in this city. 
On the other hand, though New York City used to be known for having a large amount of crime, the actual statistics paint a different story. Crime in the city has been on a downward trend since the 90s, and New York City is now considered one of the safest cities of its size. So our team considered another major city Los Angeles, home to movie stars, beaches, film studios, etc. But on the other hand, this city is also the home of some of most the infamous gangs in the world including the Crips and the Bloods. So some potential questions we wish to address include what are the most common crime types in Los Angeles, which age range of people has the most history of crime, and what kind of people is most often to be targeted as the victim, etc. 
