# Proposal

## Research topic
A city with a high violent crime rate does not indicate that the entire city is unsafe. Within each city, violence is hyper-local, meaning that violence is usually more common in specific neighborhoods or “block-by-block.”

Our team wishes to analyze Los Angeles, one of the most iconic cities in the United States, home to movie stars, film studios, amusement parks, and sunny days. Even though Los Angeles is the celebrity mecca of the entire world, violence in certain parts of Los Angeles is an everyday occurrence. Los Angeles and New York City are the two largest cities in the United States, and two of the top 13 most populated metro areas in the world. However, compared to New York City, the city of Los Angeles has a higher murder rate, and it also reports a higher rate of robberies, vandalism, and assaults. For instance, Skid Row is known for its massive homeless community. There’s also South Central and Compton, which are sub-areas plagued by gangs, shootings, and violence. The increasing crime rate has an impact on every one of us, not just Los Angeles residents, and is leading everyone to think how can we prevent these events from happening. Therefore, it raises the question of what type of crime happens the most in Los Angeles, what type of weapons are presented in the scene, and how can we do better to put the police force in certain sub-area, etc. We are hoping that by visualizing and analyzing the crime data in Los Angeles, we can apply the results to other major cities in the United States to help decrease their crime rate, and also generate insights and suggestions for strategies to prevent crimes from happening in the first place. Considering all factors, we chose to analyze the incidents of crime in the city of Los Angeles dating back to 2020 (https://data.lacity.org/Public-Safety/Crime-Data-from-2020-to-Present/2nrs-mtv8).

## Data availability
For this data analysis and visualization project, we have considered several data sources related to public health and community safety. Our incentive was to apply data analysis to generate meaningful insights into public health and safety issues. Initially, we obtained Cause of Death Dataset from Our World in Data (https://ourworldindata.org/causes-of-death), and have also considered the NYPD Shooting Incident Dataset from Data.gov(https://catalog.data.gov/dataset/nypd-shooting-incident-data-historic). After carefully analyzing the configuration of the Cause of Death Dataset, we realized that it was consisted of several related datasets, such as cause of death by disease types, breakdown of deaths by age, etc. This dataset was not provided by the original sources, and the process of selecting and combining different sources might be biased due to personal preferences of the third-party authors. For the NYPD Shooting Incident Dataset, we noticed that the columns of this dataset were limited to sex, race, and geographic locations, which might not help us understand the shooting problems from a comprehensive perspective. 

In the end, we decided to use the Crime Data from 2020 to Present provided by Los Angeles Open Data.The crime data from 2020 overcame this issue since it provided more statistics about the crime events, including victim ages, type of weapons, type of vehicles, etc. Therefore, we decided to start our study based on the crime dataset, for it not only addressed more possible factors associated with a crime, but also discussed more types of crime activities (not limited to shooting). 

In recent years, the crime and violence rate has risen to a large extent and led to great social concerns. As New York City residents, we have been concerned about public safety issues for a long time, and we would like to apply the quantitative and visualization skills we learned from class to help draw some conclusions to this problem. Potential questions we can answer from the data may include which age of people has the most history of crime, and which are the most common crime types in the city. As one of the largest cities in the States, Los Angeles also suffered from crime and violence in recent years as California’s violent crime rate increased significantly since 2020 (Magnus Lofstrom and Brandon Martin, 2022). In a nutshell, we hope that the analysis of Los Angeles crime data could provide us with a better understanding of crime events, and possibly generate insights into nationwide crime-control strategies. 

The crime dataset was provided by the Los Angeles Police Department, and transcribed from original crime reports which are typed on paper. It is available in CSV file, RDF file, JSON file, and XML file. Of these different file formats, we chose CSV because it is the most commonly used format. In order to import the data, we will first import the readr package, which runs around 10 times faster than standard r import. Since our dataset is quite large, containing around 600,000 observations, it would be beneficial to have a faster method to import data. Going into analysis, we might run into questions about the data. We can first go onto the website where the dataset is hosted to find detailed descriptions and notes about the different attributes. If the question still cannot be solved, we can contact the dataset owner, Los Angeles Police Department, via the website to resolve our confusion on the dataset.  

### Missing Values in Dataset 
After we import the data into R Studio, we noticed missing values in some of the columns. These missing values are filled with NAs. Then, we used "sapply(data, function(x) sum(is.na(x)))" to count the number of NAs in each column. Columns {Crm Cd 2, Crm Cd3, Crm Cd, Cross Street} have a significant number of values missing; therefore we will drop these four columns from our dataset. For other columns that have missing values, we will keep the NAs, but we will not draw conclusions that rely heavily on the values of these columns. 
